spring.application.name=master.on.time
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://yamanote.proxy.rlwy.net:29925\
  /railway?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=LMzjRmLglQUJLzGulCmhGdYsvaVmEwIv
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.h2.console.enabled=false
spring.liquibase.enabled=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springdoc=DEBUG
logging.level.web=DEBUG



# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
