package com.master.on.time.master.on.time.service;

import com.master.on.time.master.on.time.dto.ActivityLogDto;
import com.master.on.time.master.on.time.exception.EntityNotFoundException;
import com.master.on.time.master.on.time.model.PasswordResetToken;
import com.master.on.time.master.on.time.repository.PasswordResetTokenRepository;
import com.master.on.time.master.on.time.repository.UserRepository;
import java.time.LocalDateTime;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
@Transactional
public class AdminPasswordServiceImpl implements AdminPasswordService {

    private final PasswordResetTokenRepository tokenRepository;
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final EmailService emailService;
    private final ActivityLogService logService;

    @Override
    public String generatePasswordResetLink(Long userId) {
        if (!userRepository.existsById(userId)) {
            throw new EntityNotFoundException("User not found with id: " + userId);
        }

        String token = UUID.randomUUID().toString();

        PasswordResetToken resetToken = PasswordResetToken.builder()
                .userId(userId)
                .token(token)
                .expiryDate(LocalDateTime.now().plusHours(1))
                .build();

        tokenRepository.save(resetToken);

        String resetLink = "https://yourplatform.com/reset-password?token=" + token;

        emailService.sendPasswordResetLink(userId, resetLink);

        logService.recordLog(ActivityLogDto.builder()
                .userId(userId)
                .actionType("PASSWORD_RESET_LINK_GENERATED")
                .description("Password reset link generated by admin")
                .build());

        return resetLink;
    }

    @Override
    public void updatePasswordManually(Long userId, String newPassword) {
        var user = userRepository.findById(userId)
                .orElseThrow(()
                        -> new EntityNotFoundException("User not found with id: "
                        + userId));

        user.setPassword(passwordEncoder.encode(newPassword));
        userRepository.save(user);

        emailService.sendPasswordUpdateNotification(userId);

        logService.recordLog(ActivityLogDto.builder()
                .userId(userId)
                .actionType("PASSWORD_UPDATED_MANUALLY")
                .description("Password updated manually by admin")
                .build());
    }
}
